version: '3.3'
services:
  store:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9035:8383"
    environment:
      - TZ=America/Bahia
    restart: always
    container_name: cn_store
    volumes:
      - ./logs:/opt/app/logs
      - ./htmls:/home/portaismusiccom/resources/emails
      - /home/portaismusiccom/public_html/img/produtos:/home/portaismusiccom/public_html/img/produtos
      - /home/portaismusiccom/public_html/img/vitrine:/home/portaismusiccom/public_html/img/vitrine
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "10"
