img:
  path:
    produto: E:/loja/?/
    vitrine: E:/loja/?/
  url:
    produto: https://portaismusic.com.br/img/produtos/?/
    vitrine: https://portaismusic.com.br/img/vitrine/

resources:
  youtube: C:/desenv/projetos/loja/emails/youtube_1.png
  instagram: C:/desenv/projetos/loja/emails/instagram_1.png
  logo: C:/desenv/projetos/loja/emails/logo.png
  htmls:
    bemvindo: C:/desenv/projetos/loja/emails/confirmar-email.html
    recuperarsenha: C:/desenv/projetos/loja/emails/reenviar-senha.html
    comprarealizada: C:/desenv/projetos/loja/emails/confirmar-compra.html

server:
  port: 4343
  servlet:
    context-path: /store
spring:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/myappsservices_store?useTimezone=false&serverTimezone=GMT-3&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    idle-timeout: 15000
    maximum-pool-size: 30
    minimum-pool-size: 10
    pool-name: store-pull
  hikari:
    connection-timeout: 50000
    idle-timeout: 300000
    max-lifetime: 900000
    maximum-pool-size: 10
    minimum-idle: 10
    pool-name: ConnPool
    connection-test-query: select 1 from dual

